### PR TITLE
Add new plots in 4.3shiny_all_data

### PR DESCRIPTION
**Pull request by levubinh**
added new national plots for each output variable: 

- number of plants

- total power production

- average power production

### CODE REVIEW

**Comment by levubinh** [comment]
for your convenience:
the new codes are on line 43, line 212 to 239, and line 306

**Review by Sebaristoteles — CHANGES_REQUESTED** [review]
Hey,
why is everything green in that pull request? Have you uploaded the code as a file? This might break the Git-workflow. At least I don't understand why we cannot see the changes. I will disregard this pull request and do one using Git. Hopefully, this shows the changes.
After downloading and testing the code and testing, It's a good start to go on showing some yearly change.

**Comment by yagmurdalman** [comment]
It looks like it is all green because the file is in the main folder. It should be under `code` folder.

**Comment by levubinh** [comment]
Thank you for pointing that out. I'll see what I can do.

**Pull request closed without merging**
